### ISSUE TITLE
Getting error while writing into the bucket

### ISSUE THREAD

**Issue by hjavaid06** [GoogleCloudPlatform/gcs-fuse-csi-driver#142]
I was able to mount the bucket and view files uploaded by me manually 

but getting errors while creating or writing to any file 

error logs in **gke-gcsfuse-sidecar** container 
E1201 07:46:18.467745 CreateFile: permission denied, CreateChildFile: error in closing writer : googleapi: Error 403: Access denied., forbidden
E1201 07:46:18.467789 fuse: *fuseops.CreateFileOp error: permission denied

**Comment by Haydgoki** [comment]
Hey ! 

I'm getting the same issues on GKE. 
I installed the GCSFuse csi driver through [this tutorial] (https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#mounting-flags).
Here are my ressources  (inspired from : https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/blob/main/examples/static/pv-pvc-deploymen-non-root.yaml): 
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-gcs-csi-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dummy-storage-class
  claimRef:
    namespace: fuse
    name: gcp-gcs-csi-static-pvc
  mountOptions:
    - debug_gcs
    - debug_http
    - foreground
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: MY_BUCKET # unique bucket name
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gcp-gcs-csi-static-pvc
  namespace: fuse
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: gcp-gcs-csi-pv
  storageClassName: dummy-storage-class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-fuse
  namespace: fuse
spec:
  replicas: 3
  selector:
    matchLabels:
      app: super-fuse
  template:
    metadata:
      labels:
        app: super-fuse
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      containers:
      - name: writer
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - touch /data/${MY_POD_NAME} && while true; do echo $(date) >> /data/${MY_POD_NAME}; sleep 1; done
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-pvc
          mountPath: /data
      - name: reader
        image: busybox
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 80Mi
        command:
          - "/bin/sh"
          - "-c"
          - tail -f /data/${MY_POD_NAME}
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: gcp-gcs-csi-pvc
          mountPath: /data
          readOnly: true
      serviceAccountName: fuse
      volumes:
      - name: gcp-gcs-csi-pvc
        persistentVolumeClaim:
          claimName: gcp-gcs-csi-static-pvc
```

I'm also using my proper pod to help me to debug :
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gcs-fuse-csi-example-static-pvc
  namespace: fuse
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  containers:
  - image: busybox
    name: busybox
    command: ["sleep"]
    args: ["infinity"]
    volumeMounts:
    - name: gcp-gcs-csi-pvc
      mountPath: /data
  serviceAccountName: fuse
  volumes:
  - name: gcp-gcs-csi-pvc
    persistentVolumeClaim:
      claimName: gcp-gcs-csi-static-pvc
```

I can list files, edit files, and naviguate into directories, but It's impossible to create or delete objects :
```
# Creating file
gke-gcsfuse-sidecar D1205 15:31:23.591806 gcs: Req              0x9: <- CreateObject("oui/fds/")                                                                                                                   
gke-gcsfuse-sidecar D1205 15:31:23.604972 gcs: Req              0x9: -> CreateObject("oui/fds/") (13.159579ms): error in closing writer : googleapi: Error 403: Access denied., forbidden
# Deleting file
gke-gcsfuse-sidecar D1205 15:51:17.672623 gcs: Req             0x10: <- DeleteObject("oui/oui")                                                                                                                    
gke-gcsfuse-sidecar D1205 15:51:17.679620 gcs: Req             0x10: -> DeleteObject("oui/oui") (6.997342ms): googleapi: Error 403: Access denied., forbidden
```

I tried to : 
* Set the uid and gid and set pod security contexts
* Use the `dir-mode` and `file-mode` flags
* Disable the service account to see if it was the problem (wasn't) 
* Test the service account from local `gcsfuse` and with `gcloud storage` commands : works perfectly

I'm running out of ideas. I don't know where I missconfigured something, but the official example is failing, so I'm wondering if it's a bug or not.
