### ISSUE TITLE
The sidecar container does not respect terminationGracePeriodSeconds when the Pod restartPolicy is OnFailure or Always

### ISSUE THREAD

**Issue by songjiaxun** [GoogleCloudPlatform/gcs-fuse-csi-driver#168]
# Symptom

When the Pod `restartPolicy` is `OnFailure` or `Always`, and the Pod does not belong to a `Job` workload, the sidecar container `gke-gcsfuse-sidecar` does not respect the Pod `terminationGracePeriodSeconds`. The sidecar container will keep running until the `terminationGracePeriodSeconds` passed.

For example, the Pod `terminationGracePeriodSeconds` is set to be 60s. When you run `kubectl delete pod xxx`, the main workload container may have a logic to catch the `SIGTERM` signal, clean up, and gracefully exit in a few seconds. At this moment, the sidecar container is supposed to terminate gracefully as well because there will be no I/O that relies on the sidecar container. **However, the sidecar container will wait the full `terminationGracePeriodSeconds` 60 seconds** until Kubernetes sends the `SIGKILL` signal to forcibly kill it.

> Note that, if the Pod `restartPolicy` is `Never`, or if the Pod belongs to a `Job` workload, after all the main workload containers exit, the sidecar container will automatically terminate immediately.

# Root cause

The root cause of this behavior is that, when the sidecar container catches the `SIGTERM` signal, it does not propagate the signal to `gcsfuse` processes. Instead, the sidecar container main process will sleep and wait for the `SIGKILL` signal to forcibly kill all the `gcsfuse` processes.

Currently, `gcsfuse` cannot gracefully handle the `SIGTERM` signal -- when it receives the `SIGTERM` signal , it will terminate immediately, even though there may be in-flight I/O happening. As a result, the sidecar container main process does not propagate the signal to `gcsfuse` processes in order to avoid any data loss.

# Solution

When `gcsfuse` supports `SIGTERM` signal graceful handling, the sidecar container will propagate the signal to `gcsfuse` processes.

# Workaround

There are two workarounds to avoid this issue.

1. Consider setting the Pod `restartPolicy` to `Never` if possible.
2. In your application, add a piece of logic to notify the sidecar container to exit. Below is an example:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: gcsfuse-csi-grace-test
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: busybox
    image: busybox
    command:
      - "/bin/sh"
      - "-c"
      - handle_term() { echo "Caught SIGTERM signal! Finishig up the application!"; sleep 30; touch /gcsfuse-tmp/.volumes/exit; };
        trap handle_term SIGTERM;
        echo "I am sleeping!";
        sleep infinity & wait $!;
    volumeMounts:
    - name: gcs-fuse-csi-ephemeral
      mountPath: /data
    - name: gke-gcsfuse-tmp
      mountPath: /gcsfuse-tmp
  volumes:
  - name: gcs-fuse-csi-ephemeral
    csi:
      driver: gcsfuse.csi.storage.gke.io
      volumeAttributes:
        bucketName: your-bucket-name
```

Here is some explanation:

- The `busybox` is your main workload container.
- A volume `gke-gcsfuse-tmp` is mounted to the mount path `/gcsfuse-tmp`. You don't need to define the volume `gke-gcsfuse-tmp` because it is automatically injected by GKE.
- In your application, there is a process running in the background to catch the `SIGTERM` signal.
- When the `SIGTERM` signal is seen, your application does some clean up work.
- After the cleanup is done, your application creates a new file `/gcsfuse-tmp/.volumes/exit`.
- The sidecar container also has the volume `gke-gcsfuse-tmp` mounted, and will detect the file `/gcsfuse-tmp/.volumes/exit` and exit immediately.
- In the above example, after the main application caught the `SIGTERM` signal, it took 30 seconds to do the cleanup, and then notifies the sidecar container to exit. The Pod is able to terminate gracefully in ~ 30 seconds after the Pod delete operation.

**Comment by timscottbell** [comment]
I tested the workaround here,
```
    - name: gcs-fuse-csi-ephemeral
      mountPath: /data
```
Why add this volume mount? It won't be used by busybox.

Additionally, I don't think kubernetes will let us use a volume name that's not specified on the deployment manifest. Since `gke-gcsfuse-tmp` is not specified as a volume in the deployment manifest, I don't believe we can specify it as a volume mount, can we?

**Comment by songjiaxun** [comment]
Hi @timscottbell 

It's unfortunate to learn that the workaround does not work for a Deployment workload. In this case, you will have to manually inject the entire sidecar container spec. Here is an example:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcsfuse-csi-grace-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcsfuse-csi-grace-test
  template:
    metadata:
      name: gcsfuse-csi-grace-test
      labels:
        app: gcsfuse-csi-grace-test
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - args:
        - --v=5
        image: gcr.io/gke-release/gcs-fuse-csi-driver-sidecar-mounter@sha256:972699a4bf8973f7614f09908412a1fca24ea939eac2d3fcca599109f71fc162
        imagePullPolicy: IfNotPresent
        name: gke-gcsfuse-sidecar
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
          readOnlyRootFilesystem: true
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /gcsfuse-tmp
          name: gke-gcsfuse-tmp
        - mountPath: /gcsfuse-buffer
          name: gke-gcsfuse-buffer
      - name: busybox
        image: busybox
        resources: {}
        command:
          - "/bin/sh"
          - "-c"
          - handle_term() { echo "Caught SIGTERM signal! Finishig up the application!"; sleep 10; touch /gcsfuse-tmp/.volumes/exit; };
            trap handle_term SIGTERM;
            echo "I am sleeping!";
            sleep infinity & wait $!;
        volumeMounts:
        - name: gcs-fuse-csi-ephemeral
          mountPath: /data
        - name: gke-gcsfuse-tmp
          mountPath: /gcsfuse-tmp
      volumes:
      - name: gcs-fuse-csi-ephemeral
        csi:
          driver: gcsfuse.csi.storage.gke.io
          volumeAttributes:
            bucketName: your-bucket-name
      - name: gke-gcsfuse-tmp
        emptyDir: {}
      - name: gke-gcsfuse-buffer
        emptyDir: {}
```

Note that:
- You must remove the annotation `gke-gcsfuse/volumes: "true"` from the template.
- The sidecar container `gke-gcsfuse-sidecar` needs to be the first container.
- You will need to define two emptyDir volumes `gke-gcsfuse-tmp` and `gke-gcsfuse-buffer`/
- This workaround still relies on the `exit file` to terminate the sidecar container.
