### ISSUE TITLE
Enabling file cache without webhook injector

### ISSUE THREAD

**Issue by christopher-kwan-541** [GoogleCloudPlatform/gcs-fuse-csi-driver#207]
The webhook injector specifies an `EmptyDir` as the cache directory and I would prefer to be able to specify a persistent volume so that I can readily increase the size of my cache depending on my reading pattern.

Trying to work around this by specifying the `gcs-gkefuse-sidecar` container on my own instead of using the pod annotations. This allows me to specify which particular version of the CSI driver to use (trying out v1.2.0 right now) and also to specify the cache dir as an ephemeral volume.

This is however still failing: `rpc error: code = FailedPrecondition desc = failed to find the sidecar container in Pod spec`.

Any idea if this idea is feasible at all? The below is an example of the YAML definition I am using:

<details>
<summary>Details</summary>

```
	containers:
      - name: gke-gcsfuse-sidecar
        image: <REGISTRY>/gcs-fuse-csi-driver-sidecar-mounter:v1.2.0
        imagePullPolicy: IfNotPresent
        args:
        - --v=5
        - --grace-period=30
        volumeMounts:
        - mountPath: /gcsfuse-buffer
          name: gke-gcsfuse-buffer
        - mountPath: /gcsfuse-tmp
          name: gke-gcsfuse-tmp
        - mountPath: /gcsfuse-cache
          name: cachedir
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65534
          runAsNonRoot: true
          runAsUser: 65534
     ....
     ....
	volumes:
	- ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                type: main-volume
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 100Gi
              storageClassName: standard
	        name: cachedir
    - csi:
        driver: gcsfuse.csi.storage.gke.io
        readOnly: true
        volumeAttributes:
          bucketName: <some_output_bucket>
          fileCacheCapacity: "-1"
          fileCacheForRangeRead: "true"
          metadataStatCacheCapacity: "-1"
          metadataTypeCacheCapacity: "-1"
          metadataCacheTTLSeconds: "-1"
          mountOptions: implicit-dirs,only-dir=<some_dir>,logging:severity:info
      name: fuse-dir
    - name: gke-gcsfuse-tmp
      emptyDir: {}
    - name: gke-gcsfuse-buffer
      emptyDir: {}
```

</details>
