### ISSUE TITLE
Custom sidecar container image crashes the CSI driver

### ISSUE THREAD

**Issue by songjiaxun** [GoogleCloudPlatform/gcs-fuse-csi-driver#233]
## Symptom

When a custom sidecar container image is specified following the [GKE doc](https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/cloud-storage-fuse-csi-driver#private-image), in rare cases, the CSI node may crash with `invalid memory address or nil pointer dereferrence` errors. 

## Workaround

Please add a `securityContext` section to the sidecar container to specify a `runAsGroup` and `runAsUser`, for example:

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    gke-gcsfuse/volumes: "true"
spec:
  containers:
  - name: gke-gcsfuse-sidecar
    image: PRIVATE_REGISTRY/gcs-fuse-csi-driver-sidecar-mounter:PRIVATE_IMAGE_TAG
    securityContext:
      runAsGroup: 65534
      runAsUser: 65534
  - name: main # your main workload container.
```

## Fixes

This issue is patched and pending for release.
