### ISSUE TITLE
FUSE CSI driver using native sidecar mutates restart policy on wrong init container

### ISSUE THREAD

**Issue by Baune8D** [GoogleCloudPlatform/gcs-fuse-csi-driver#296]
We ran into this problem after upgrading our AutoPilot cluster from K8s 1.28.7 to 1.29.4.

We also run managed Anthos Service Mesh v1.18.7

When deploying pods using both FUSE CSI driver and Istio proxy, `restartPolicy` gets mutated to `always` on `istio-validation` init container instead of `gke-gcsfuse-sidecar`.

### Manifest: FUSE CSI driver: `enabled` - Istio sidecar injection: `enabled`

Notice `restartPolicy: always` gets applied to `istio-validation` init container, and not to `gke-gcsfuse-sidecar`

```yaml
initContainers:
  - args:
      - istio-iptables
      - '-p'
      - '15001'
      - '-z'
      - '15006'
      - '-u'
      - '1337'
      - '-m'
      - REDIRECT
      - '-i'
      - '*'
      - '-x'
      - ''
      - '-b'
      - '*'
      - '-d'
      - '15090,15021,15020'
      - '--log_output_level=default:info'
      - '--run-validation'
      - '--skip-rule-apply'
    env:
      - name: CA_PROVIDER
        value: GoogleCA
      - name: CA_ROOT_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - name: CA_TRUSTANCHOR
      - name: EXIT_ON_ZERO_ACTIVE_CONNECTIONS
        value: 'true'
      - name: FLEET_PROJECT_NUMBER
        value: 'xxx'
      - name: GCP_METADATA
        value: xxx|xxx|xxx|xxx
      - name: OUTPUT_CERTS
        value: /etc/istio/proxy
      - name: PROXY_CONFIG_XDS_AGENT
        value: 'true'
      - name: XDS_AUTH_PROVIDER
        value: gcp
      - name: XDS_ROOT_CA
        value: /etc/ssl/certs/ca-certificates.crt
    image: 'gcr.io/gke-release/asm/proxyv2:1.18.7-asm.21'
    imagePullPolicy: IfNotPresent
    name: istio-validation
    resources:
      limits:
        cpu: 500m
        ephemeral-storage: 1Gi
        memory: 512Mi
      requests:
        cpu: 500m
        ephemeral-storage: 1Gi
        memory: 512Mi
    restartPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-n6xh7
        readOnly: true
  - args:
      - '--v=5'
    env:
      - name: NATIVE_SIDECAR
        value: 'TRUE'
    image: >-
      gke.gcr.io/gcs-fuse-csi-driver-sidecar-mounter:v1.2.0-gke.0@sha256:31880114306b1fb5d9e365ae7d4771815ea04eb56f0464a514a810df9470f88f
    imagePullPolicy: IfNotPresent
    name: gke-gcsfuse-sidecar
    resources:
      limits:
        cpu: 250m
        ephemeral-storage: 5Gi
        memory: 256Mi
      requests:
        cpu: 250m
        ephemeral-storage: 5Gi
        memory: 256Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /gcsfuse-tmp
        name: gke-gcsfuse-tmp
      - mountPath: /gcsfuse-buffer
        name: gke-gcsfuse-buffer
      - mountPath: /gcsfuse-cache
        name: gke-gcsfuse-cache
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-n6xh7
        readOnly: true
```

### Manifest: FUSE CSI driver: `disabled` - Istio sidecar injection: `enabled`

This time there is no `restartPolicy: always` on the `istio-validation` init container.

```yaml
initContainers:
  - args:
      - istio-iptables
      - '-p'
      - '15001'
      - '-z'
      - '15006'
      - '-u'
      - '1337'
      - '-m'
      - REDIRECT
      - '-i'
      - '*'
      - '-x'
      - ''
      - '-b'
      - '*'
      - '-d'
      - '15090,15021,15020'
      - '--log_output_level=default:info'
      - '--run-validation'
      - '--skip-rule-apply'
    env:
      - name: CA_PROVIDER
        value: GoogleCA
      - name: CA_ROOT_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - name: CA_TRUSTANCHOR
      - name: EXIT_ON_ZERO_ACTIVE_CONNECTIONS
        value: 'true'
      - name: FLEET_PROJECT_NUMBER
        value: 'xxx'
      - name: GCP_METADATA
        value: xxx|xxx|xxx|xxx
      - name: OUTPUT_CERTS
        value: /etc/istio/proxy
      - name: PROXY_CONFIG_XDS_AGENT
        value: 'true'
      - name: XDS_AUTH_PROVIDER
        value: gcp
      - name: XDS_ROOT_CA
        value: /etc/ssl/certs/ca-certificates.crt
    image: 'gcr.io/gke-release/asm/proxyv2:1.18.7-asm.21'
    imagePullPolicy: IfNotPresent
    name: istio-validation
    resources:
      limits:
        cpu: 500m
        ephemeral-storage: 1152Mi
        memory: 512Mi
      requests:
        cpu: 500m
        ephemeral-storage: 1152Mi
        memory: 512Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-fpcmd
        readOnly: true
```

### Manifest: FUSE CSI driver: ´enabled` - Istio sidecar injection: `disabled`

Now the FUSE CSI driver sidecar contains `restartPolicy: always` as expected

```yaml
initContainers:
  - args:
      - '--v=5'
    env:
      - name: NATIVE_SIDECAR
        value: 'TRUE'
    image: >-
      gke.gcr.io/gcs-fuse-csi-driver-sidecar-mounter:v1.2.0-gke.0@sha256:31880114306b1fb5d9e365ae7d4771815ea04eb56f0464a514a810df9470f88f
    imagePullPolicy: IfNotPresent
    name: gke-gcsfuse-sidecar
    resources:
      limits:
        cpu: 250m
        ephemeral-storage: 5Gi
        memory: 256Mi
      requests:
        cpu: 250m
        ephemeral-storage: 5Gi
        memory: 256Mi
    restartPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
      - mountPath: /gcsfuse-tmp
        name: gke-gcsfuse-tmp
      - mountPath: /gcsfuse-buffer
        name: gke-gcsfuse-buffer
      - mountPath: /gcsfuse-cache
        name: gke-gcsfuse-cache
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-rcxtp
        readOnly: true
```

This manifests as the same symptoms as seen here: https://github.com/GoogleCloudPlatform/gcs-fuse-csi-driver/issues/53#issuecomment-2075057210
