### ISSUE TITLE
File exists error returned on OS level even when file doesn't exist

### ISSUE THREAD

**Issue by andrzejbylicki** [GoogleCloudPlatform/gcs-fuse-csi-driver#315]
**Describe the issue**
I am attempting to save Python `pytest` run results from a Kubernetes CronJob deployment in Google Kubernetes Engine on a Google Cloud Storage bucket mounted as an ephemeral volume. Below are the relevant sections of the YAML:
```yaml
spec:
  backoffLimit: 2
  template:
    metadata:
      annotations:
        gke-gcsfuse/volumes: "true"
    spec:
      serviceAccountName: google-bucket-user
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      volumes:
        - name: gcs-fuse-csi-ephemeral
          csi:
            driver: gcsfuse.csi.storage.gke.io
            volumeAttributes:
              bucketName: name_of_bucket
              mountOptions: "debug_gcs,debug_fuse,implicit-dirs,only-dir=scheduled_tasks"
              gcsfuseLoggingSeverity: warning
      containers:
      - name: pytest-pod
        image: ubuntu:22.04
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
        command:
        - /bin/bash
        - -c
        args:
        - |
          pushd /opt/tasks &&
          python -m pytest &&
          cp -r test_results /opt/tmp/ &&
          popd
        volumeMounts:
        # Storage for test results
        - name: gcs-fuse-csi-ephemeral
          mountPath: /opt/tmp/test_results
      restartPolicy: Never
```

**Debug logs**
```json
{"timestamp":{"seconds":1721316858,"nanos":660380473},"severity":"INFO","message":"Creating Storage handle..."}
{"timestamp":{"seconds":1721316858,"nanos":660388640},"severity":"INFO","message":"UserAgent = gcsfuse/2.0.1-gke.0 (Go version go1.22.1) (GPN:gcsfuse-gke-gcs-fuse-csi) (Cfg:0:0)\n"}
{"timestamp":{"seconds":1721316858,"nanos":665112655},"severity":"INFO","message":"Creating a mount at \"/dev/fd/3\"\n"}
{"timestamp":{"seconds":1721316858,"nanos":665142025},"severity":"INFO","message":"Creating a temporary directory at \"/gcsfuse-buffer/.volumes/gcs-fuse-csi-ephemeral/temp-dir\"\n"}
{"timestamp":{"seconds":1721316858,"nanos":665262715},"severity":"INFO","message":"Creating a new server...\n"}
{"timestamp":{"seconds":1721316858,"nanos":665315184},"severity":"INFO","message":"Set up root directory for bucket cloud-awattar-procurement_test_results"}
{"timestamp":{"seconds":1721316858,"nanos":665377961},"severity":"TRACE","message":"gcs: Req              0x0: <- ListObjects(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/\")"}
{"timestamp":{"seconds":1721316858,"nanos":863290132},"severity":"TRACE","message":"gcs: Req              0x0: -> ListObjects(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/\") (197.902992ms): OK"}
{"timestamp":{"seconds":1721316858,"nanos":863374873},"severity":"INFO","message":"Mounting file system \"cloud-awattar-procurement_test_results\"..."}
{"timestamp":{"seconds":1721316858,"nanos":863403490},"severity":"TRACE","message":"fuse_debug: Beginning the mounting kickoff process"}
{"timestamp":{"seconds":1721316858,"nanos":863421727},"severity":"TRACE","message":"fuse_debug: Parsing fuse file descriptor"}
{"timestamp":{"seconds":1721316858,"nanos":863434514},"severity":"TRACE","message":"fuse_debug: Completed the mounting kickoff process"}
{"timestamp":{"seconds":1721316858,"nanos":863443273},"severity":"TRACE","message":"fuse_debug: Creating a connection object"}
{"timestamp":{"seconds":1721316858,"nanos":863951282},"severity":"TRACE","message":"fuse_debug: Op 0x00000002        connection.go:415] <- init"}
{"timestamp":{"seconds":1721316858,"nanos":864213820},"severity":"TRACE","message":"fuse_debug: Op 0x00000002        connection.go:497] -> OK ()"}
{"timestamp":{"seconds":1721316858,"nanos":864312029},"severity":"TRACE","message":"fuse_debug: Successfully created the connection"}
{"timestamp":{"seconds":1721316858,"nanos":864381550},"severity":"TRACE","message":"fuse_debug: Waiting for mounting process to complete"}
{"timestamp":{"seconds":1721316858,"nanos":864440896},"severity":"INFO","message":"File system has been successfully mounted."}
{"timestamp":{"seconds":1721316858,"nanos":864693791},"severity":"TRACE","message":"fuse_debug: Op 0x00000004        connection.go:415] <- GetInodeAttributes (inode 1, PID 0)"}
{"timestamp":{"seconds":1721316858,"nanos":864975387},"severity":"TRACE","message":"fuse_debug: Op 0x00000004        connection.go:497] -> OK ()"}
{"timestamp":{"seconds":1721316868,"nanos":365366830},"severity":"TRACE","message":"fuse_debug: Op 0x00000006        connection.go:415] <- LookUpInode (parent 1, name \"assets\", PID 0)"}
{"timestamp":{"seconds":1721316868,"nanos":365523749},"severity":"TRACE","message":"gcs: Req              0x2: <- StatObject(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/assets\")"}
{"timestamp":{"seconds":1721316868,"nanos":365523742},"severity":"TRACE","message":"gcs: Req              0x1: <- ListObjects(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/assets/\")"}
{"timestamp":{"seconds":1721316868,"nanos":388128815},"severity":"TRACE","message":"gcs: Req              0x2: -> StatObject(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/assets\") (22.597137ms): gcs.NotFoundError: storage: object doesn't exist"}
{"timestamp":{"seconds":1721316868,"nanos":418959323},"severity":"TRACE","message":"gcs: Req              0x1: -> ListObjects(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/assets/\") (53.4342ms): OK"}
{"timestamp":{"seconds":1721316868,"nanos":419067110},"severity":"TRACE","message":"fuse_debug: Op 0x00000006        connection.go:499] -> Error: \"no such file or directory\""}
{"timestamp":{"seconds":1721316868,"nanos":419252459},"severity":"TRACE","message":"fuse_debug: Op 0x00000008        connection.go:415] <- LookUpInode (parent 1, name \"assets\", PID 0)"}
{"timestamp":{"seconds":1721316868,"nanos":419364328},"severity":"TRACE","message":"gcs: Req              0x3: <- ListObjects(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/assets/\")"}
{"timestamp":{"seconds":1721316868,"nanos":444863248},"severity":"TRACE","message":"gcs: Req              0x3: -> ListObjects(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/assets/\") (25.497721ms): OK"}
{"timestamp":{"seconds":1721316868,"nanos":444953650},"severity":"TRACE","message":"fuse_debug: Op 0x00000008        connection.go:499] -> Error: \"no such file or directory\""}
{"timestamp":{"seconds":1721316868,"nanos":445168938},"severity":"TRACE","message":"fuse_debug: Op 0x0000000a        connection.go:415] <- MkDir (parent 1, name \"assets\", PID 0)"}
{"timestamp":{"seconds":1721316868,"nanos":447730356},"severity":"TRACE","message":"gcs: Req              0x4: <- CreateObject(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/assets/\")"}
{"timestamp":{"seconds":1721316868,"nanos":500947943},"severity":"TRACE","message":"gcs: Req              0x4: -> CreateObject(\"scheduled_tasks/633d12adef153e39e5bbc3c954c356022616f179/assets/\") (53.19009ms): gcs.PreconditionError: googleapi: Error 412: The type of authentication token used for this request requires that Uniform Bucket Level Access be enabled., conditionNotMet"}
{"timestamp":{"seconds":1721316868,"nanos":501040195},"severity":"TRACE","message":"fuse_debug: Op 0x0000000a        connection.go:499] -> Error: \"file exists\""}
{"timestamp":{"seconds":1721316868,"nanos":501056093},"severity":"ERROR","message":"fuse: *fuseops.MkDirOp error: file exists"}
```

**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Platform: Google Kubernetes Engine (GKE)
 - Version v1.29.5-gke.1091002
 
 **Additional context**
 It seems like File exists is being returned even though the actual problem might be related to the access level settings on the bucket itself?
